// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct BattleDamageTakenResultData {
  uint256 hpAtStart;
  uint256 damageTaken;
}

library BattleDamageTakenResult {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "Pri_11", name: "BattleDamageTake", typeId: RESOURCE_OFFCHAIN_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x6f745072695f31310000000000000000426174746c6544616d61676554616b65);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0040020020200000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004002005f5f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x004002001f1f0000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "battleEntity";
    keyNames[1] = "participantEntity";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "hpAtStart";
    fieldNames[1] = "damageTaken";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Set hpAtStart.
   */
  function setHpAtStart(bytes32 battleEntity, bytes32 participantEntity, uint256 hpAtStart) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((hpAtStart)), _fieldLayout);
  }

  /**
   * @notice Set hpAtStart.
   */
  function _setHpAtStart(bytes32 battleEntity, bytes32 participantEntity, uint256 hpAtStart) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((hpAtStart)), _fieldLayout);
  }

  /**
   * @notice Set damageTaken.
   */
  function setDamageTaken(bytes32 battleEntity, bytes32 participantEntity, uint256 damageTaken) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((damageTaken)), _fieldLayout);
  }

  /**
   * @notice Set damageTaken.
   */
  function _setDamageTaken(bytes32 battleEntity, bytes32 participantEntity, uint256 damageTaken) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((damageTaken)), _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 battleEntity, bytes32 participantEntity, uint256 hpAtStart, uint256 damageTaken) internal {
    bytes memory _staticData = encodeStatic(hpAtStart, damageTaken);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 battleEntity, bytes32 participantEntity, uint256 hpAtStart, uint256 damageTaken) internal {
    bytes memory _staticData = encodeStatic(hpAtStart, damageTaken);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 battleEntity, bytes32 participantEntity, BattleDamageTakenResultData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.hpAtStart, _table.damageTaken);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 battleEntity, bytes32 participantEntity, BattleDamageTakenResultData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.hpAtStart, _table.damageTaken);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint256 hpAtStart, uint256 damageTaken) {
    hpAtStart = (uint256(Bytes.getBytes32(_blob, 0)));

    damageTaken = (uint256(Bytes.getBytes32(_blob, 32)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (BattleDamageTakenResultData memory _table) {
    (_table.hpAtStart, _table.damageTaken) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 battleEntity, bytes32 participantEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 battleEntity, bytes32 participantEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 hpAtStart, uint256 damageTaken) internal pure returns (bytes memory) {
    return abi.encodePacked(hpAtStart, damageTaken);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 hpAtStart,
    uint256 damageTaken
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(hpAtStart, damageTaken);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 battleEntity, bytes32 participantEntity) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = battleEntity;
    _keyTuple[1] = participantEntity;

    return _keyTuple;
  }
}
