// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct P_GameConfigData {
  address admin;
  uint256 unitProductionRate;
  uint256 travelTime;
  uint256 worldSpeed;
  uint256 maxAsteroidsPerPlayer;
  uint256 asteroidChanceInv;
  uint256 asteroidDistance;
  uint256 unitDeathLimit;
}

library P_GameConfig {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "Pri_11", name: "P_GameConfig", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74625072695f31310000000000000000505f47616d65436f6e66696700000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x00f4080014202020202020200000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, uint256, uint256, uint256, uint256, uint256, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x00f40800611f1f1f1f1f1f1f0000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](8);
    fieldNames[0] = "admin";
    fieldNames[1] = "unitProductionRate";
    fieldNames[2] = "travelTime";
    fieldNames[3] = "worldSpeed";
    fieldNames[4] = "maxAsteroidsPerPlayer";
    fieldNames[5] = "asteroidChanceInv";
    fieldNames[6] = "asteroidDistance";
    fieldNames[7] = "unitDeathLimit";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get admin.
   */
  function getAdmin() internal view returns (address admin) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get admin.
   */
  function _getAdmin() internal view returns (address admin) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set admin.
   */
  function setAdmin(address admin) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((admin)), _fieldLayout);
  }

  /**
   * @notice Set admin.
   */
  function _setAdmin(address admin) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((admin)), _fieldLayout);
  }

  /**
   * @notice Get unitProductionRate.
   */
  function getUnitProductionRate() internal view returns (uint256 unitProductionRate) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get unitProductionRate.
   */
  function _getUnitProductionRate() internal view returns (uint256 unitProductionRate) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set unitProductionRate.
   */
  function setUnitProductionRate(uint256 unitProductionRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((unitProductionRate)), _fieldLayout);
  }

  /**
   * @notice Set unitProductionRate.
   */
  function _setUnitProductionRate(uint256 unitProductionRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((unitProductionRate)), _fieldLayout);
  }

  /**
   * @notice Get travelTime.
   */
  function getTravelTime() internal view returns (uint256 travelTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get travelTime.
   */
  function _getTravelTime() internal view returns (uint256 travelTime) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set travelTime.
   */
  function setTravelTime(uint256 travelTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((travelTime)), _fieldLayout);
  }

  /**
   * @notice Set travelTime.
   */
  function _setTravelTime(uint256 travelTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((travelTime)), _fieldLayout);
  }

  /**
   * @notice Get worldSpeed.
   */
  function getWorldSpeed() internal view returns (uint256 worldSpeed) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get worldSpeed.
   */
  function _getWorldSpeed() internal view returns (uint256 worldSpeed) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set worldSpeed.
   */
  function setWorldSpeed(uint256 worldSpeed) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((worldSpeed)), _fieldLayout);
  }

  /**
   * @notice Set worldSpeed.
   */
  function _setWorldSpeed(uint256 worldSpeed) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((worldSpeed)), _fieldLayout);
  }

  /**
   * @notice Get maxAsteroidsPerPlayer.
   */
  function getMaxAsteroidsPerPlayer() internal view returns (uint256 maxAsteroidsPerPlayer) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get maxAsteroidsPerPlayer.
   */
  function _getMaxAsteroidsPerPlayer() internal view returns (uint256 maxAsteroidsPerPlayer) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set maxAsteroidsPerPlayer.
   */
  function setMaxAsteroidsPerPlayer(uint256 maxAsteroidsPerPlayer) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((maxAsteroidsPerPlayer)), _fieldLayout);
  }

  /**
   * @notice Set maxAsteroidsPerPlayer.
   */
  function _setMaxAsteroidsPerPlayer(uint256 maxAsteroidsPerPlayer) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((maxAsteroidsPerPlayer)), _fieldLayout);
  }

  /**
   * @notice Get asteroidChanceInv.
   */
  function getAsteroidChanceInv() internal view returns (uint256 asteroidChanceInv) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get asteroidChanceInv.
   */
  function _getAsteroidChanceInv() internal view returns (uint256 asteroidChanceInv) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set asteroidChanceInv.
   */
  function setAsteroidChanceInv(uint256 asteroidChanceInv) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((asteroidChanceInv)), _fieldLayout);
  }

  /**
   * @notice Set asteroidChanceInv.
   */
  function _setAsteroidChanceInv(uint256 asteroidChanceInv) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((asteroidChanceInv)), _fieldLayout);
  }

  /**
   * @notice Get asteroidDistance.
   */
  function getAsteroidDistance() internal view returns (uint256 asteroidDistance) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get asteroidDistance.
   */
  function _getAsteroidDistance() internal view returns (uint256 asteroidDistance) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set asteroidDistance.
   */
  function setAsteroidDistance(uint256 asteroidDistance) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((asteroidDistance)), _fieldLayout);
  }

  /**
   * @notice Set asteroidDistance.
   */
  function _setAsteroidDistance(uint256 asteroidDistance) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((asteroidDistance)), _fieldLayout);
  }

  /**
   * @notice Get unitDeathLimit.
   */
  function getUnitDeathLimit() internal view returns (uint256 unitDeathLimit) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get unitDeathLimit.
   */
  function _getUnitDeathLimit() internal view returns (uint256 unitDeathLimit) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set unitDeathLimit.
   */
  function setUnitDeathLimit(uint256 unitDeathLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((unitDeathLimit)), _fieldLayout);
  }

  /**
   * @notice Set unitDeathLimit.
   */
  function _setUnitDeathLimit(uint256 unitDeathLimit) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((unitDeathLimit)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (P_GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (P_GameConfigData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    address admin,
    uint256 unitProductionRate,
    uint256 travelTime,
    uint256 worldSpeed,
    uint256 maxAsteroidsPerPlayer,
    uint256 asteroidChanceInv,
    uint256 asteroidDistance,
    uint256 unitDeathLimit
  ) internal {
    bytes memory _staticData = encodeStatic(
      admin,
      unitProductionRate,
      travelTime,
      worldSpeed,
      maxAsteroidsPerPlayer,
      asteroidChanceInv,
      asteroidDistance,
      unitDeathLimit
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    address admin,
    uint256 unitProductionRate,
    uint256 travelTime,
    uint256 worldSpeed,
    uint256 maxAsteroidsPerPlayer,
    uint256 asteroidChanceInv,
    uint256 asteroidDistance,
    uint256 unitDeathLimit
  ) internal {
    bytes memory _staticData = encodeStatic(
      admin,
      unitProductionRate,
      travelTime,
      worldSpeed,
      maxAsteroidsPerPlayer,
      asteroidChanceInv,
      asteroidDistance,
      unitDeathLimit
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(P_GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.admin,
      _table.unitProductionRate,
      _table.travelTime,
      _table.worldSpeed,
      _table.maxAsteroidsPerPlayer,
      _table.asteroidChanceInv,
      _table.asteroidDistance,
      _table.unitDeathLimit
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(P_GameConfigData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.admin,
      _table.unitProductionRate,
      _table.travelTime,
      _table.worldSpeed,
      _table.maxAsteroidsPerPlayer,
      _table.asteroidChanceInv,
      _table.asteroidDistance,
      _table.unitDeathLimit
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      address admin,
      uint256 unitProductionRate,
      uint256 travelTime,
      uint256 worldSpeed,
      uint256 maxAsteroidsPerPlayer,
      uint256 asteroidChanceInv,
      uint256 asteroidDistance,
      uint256 unitDeathLimit
    )
  {
    admin = (address(Bytes.getBytes20(_blob, 0)));

    unitProductionRate = (uint256(Bytes.getBytes32(_blob, 20)));

    travelTime = (uint256(Bytes.getBytes32(_blob, 52)));

    worldSpeed = (uint256(Bytes.getBytes32(_blob, 84)));

    maxAsteroidsPerPlayer = (uint256(Bytes.getBytes32(_blob, 116)));

    asteroidChanceInv = (uint256(Bytes.getBytes32(_blob, 148)));

    asteroidDistance = (uint256(Bytes.getBytes32(_blob, 180)));

    unitDeathLimit = (uint256(Bytes.getBytes32(_blob, 212)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (P_GameConfigData memory _table) {
    (
      _table.admin,
      _table.unitProductionRate,
      _table.travelTime,
      _table.worldSpeed,
      _table.maxAsteroidsPerPlayer,
      _table.asteroidChanceInv,
      _table.asteroidDistance,
      _table.unitDeathLimit
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address admin,
    uint256 unitProductionRate,
    uint256 travelTime,
    uint256 worldSpeed,
    uint256 maxAsteroidsPerPlayer,
    uint256 asteroidChanceInv,
    uint256 asteroidDistance,
    uint256 unitDeathLimit
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        admin,
        unitProductionRate,
        travelTime,
        worldSpeed,
        maxAsteroidsPerPlayer,
        asteroidChanceInv,
        asteroidDistance,
        unitDeathLimit
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address admin,
    uint256 unitProductionRate,
    uint256 travelTime,
    uint256 worldSpeed,
    uint256 maxAsteroidsPerPlayer,
    uint256 asteroidChanceInv,
    uint256 asteroidDistance,
    uint256 unitDeathLimit
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      admin,
      unitProductionRate,
      travelTime,
      worldSpeed,
      maxAsteroidsPerPlayer,
      asteroidChanceInv,
      asteroidDistance,
      unitDeathLimit
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
