// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EAllianceInviteMode, EAllianceRole } from "src/Types.sol";

/**
 * @title IAllianceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAllianceSystem {
  function Primodium__join(bytes32 alliance) external;

  function Primodium__create(
    bytes32 name,
    EAllianceInviteMode allianceInviteMode
  ) external returns (bytes32 allianceEntity);

  function Primodium__leave() external;

  function Primodium__invite(address target) external;

  function Primodium__revokeInvite(address target) external;

  function Primodium__declineInvite(address inviter) external;

  function Primodium__kick(address target) external;

  function Primodium__grantRole(address target, EAllianceRole role) external;

  function Primodium__requestToJoin(bytes32 alliance) external;

  function Primodium__rejectRequestToJoin(address rejectee) external;

  function Primodium__acceptRequestToJoin(address accepted) external;
}
