// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "primodium/index.sol";

/**
 * @title IFleetMoveSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetMoveSystem {
  function Primodium__sendFleet(bytes32 fleetEntity, PositionData memory position) external;

  function Primodium__sendFleet(bytes32 fleetEntity, bytes32 asteroidEntity) external;
}
