// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFleetStanceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetStanceSystem {
  function Primodium__clearFleetStance(bytes32 fleetEntity) external;

  function Primodium__setFleetStance(bytes32 fleetEntity, uint8 stance, bytes32 target) external;
}
