// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "primodium/index.sol";

/**
 * @title IMoveBuildingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMoveBuildingSystem {
  function Primodium__moveBuilding(bytes32 buildingEntity, PositionData memory toCoord) external;
}
