// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_ClaimSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_ClaimSystem {
  function Primodium__claimUnits(bytes32 asteroidEntity) external;

  function Primodium__claimResources(bytes32 asteroidEntity) external;
}
