// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetResolvePirateAsteroidSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetResolvePirateAsteroidSystem {
  function Primodium__resolvePirateAsteroid(bytes32 playerEntity, bytes32 pirateAsteroid) external;
}
