// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_SpendResourcesSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_SpendResourcesSystem {
  function Primodium__spendBuildingRequiredResources(bytes32 buildingEntity, uint256 level) external;

  function Primodium__spendUpgradeResources(bytes32 asteroidEntity, bytes32 upgradePrototype, uint256 level) external;

  function Primodium__toggleBuildingUtility(bytes32 buildingEntity) external;

  function Primodium__clearUtilityUsage(bytes32 buildingEntity) external;
}
