// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_SpawnPirateAsteroidSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_SpawnPirateAsteroidSystem {
  function Primodium__spawnPirateAsteroid(
    bytes32 playerEntity,
    bytes32 prototypeEntity
  ) external returns (bytes32 asteroidEntity);
}
