// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITransferSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITransferSystem {
  function Primodium__transferUnitsFromAsteroidToFleet(
    bytes32 asteroidEntity,
    bytes32 fleetEntity,
    uint256[] calldata unitCounts
  ) external;

  function Primodium__transferResourcesFromAsteroidToFleet(
    bytes32 asteroidEntity,
    bytes32 fleetEntity,
    uint256[] calldata resourceCounts
  ) external;

  function Primodium__transferUnitsAndResourcesFromAsteroidToFleet(
    bytes32 asteroidEntity,
    bytes32 fleetEntity,
    uint256[] calldata unitCounts,
    uint256[] calldata resourceCounts
  ) external;

  function Primodium__transferUnitsFromFleetToAsteroid(
    bytes32 fromFleetEntity,
    bytes32 asteroidEntity,
    uint256[] calldata unitCounts
  ) external;

  function Primodium__transferResourcesFromFleetToAsteroid(
    bytes32 fleetEntity,
    bytes32 asteroidEntity,
    uint256[] calldata resourceCounts
  ) external;

  function Primodium__transferUnitsAndResourcesFromFleetToAsteroid(
    bytes32 fromFleetEntity,
    bytes32 asteroidEntity,
    uint256[] calldata unitCounts,
    uint256[] calldata resourceCounts
  ) external;

  function Primodium__transferUnitsFromFleetToFleet(
    bytes32 fromFleetEntity,
    bytes32 toFleetEntity,
    uint256[] calldata unitCounts
  ) external;

  function Primodium__transferResourcesFromFleetToFleet(
    bytes32 fromFleetEntity,
    bytes32 toFleetEntity,
    uint256[] calldata resourceCounts
  ) external;

  function Primodium__transferUnitsAndResourcesFromFleetToFleet(
    bytes32 fromFleetEntity,
    bytes32 toFleetEntity,
    uint256[] calldata unitCounts,
    uint256[] calldata resourceCounts
  ) external;
}
